<template>
  <div class="home">
    <section class="d-flex landing_page align-items-center">
      <img src="/img/henrysmile.jpeg" width="300" class="img" alt="a picture of Eze Henry(godofjs) smiling"/>
      <div class="text_container">
        <div class="header pb-4">
          Hey,<br />
          I am Henry
        </div>
        <div class="col-lg-8 col-sm-12 p-0 text_sm">
          I build Enterprise full stack applications, and of course I am a
          technical writer.
        </div>
        <div class="pt-5 font_sm">
          You can reach me via my social media handles:
        </div>
        <div class="pt-4 d-flex align-items-center socials">
          <a href="https://twitter.com/godofjs" target="_blank"
            ><button class="mdi-twitter mdi trans_btn"></button>
          </a>
          <a href="https://www.instagram.com/_henry_eze/" target="_blank"
            ><button class="mdi-instagram mdi trans_btn"></button>
          </a>
          <a
            href="https://www.linkedin.com/in/henry-eze-1b1385185/"
            target="_blank"
            ><button class="mdi-linkedin mdi trans_btn"></button>
          </a>
          <a href="https://github.com/god-of-js" target="_blank"
            ><button class="mdi-github mdi trans_btn"></button>
          </a>
          <a href="https://medium.com/@Godofjs" target="_blank">
            <button class="trans_btn">
            <span class="iconify" data-icon="mdi-medium" data-inline="false"></span>
            </button>
          </a>
        </div>
      </div>
    </section>
    <section class="pl-5 pt-5 pr-5 pb-2 no_padding">
      <div class="title no_padding text-center pb-5">Projects</div>
      <div>
        <postt v-for="(project, index) in projects" :key="index" :type="'project'" :name="project.name" :text="project.text" :languages="project.language" :link="project.link"/>
      </div>
    </section>
    <section class="pl-5 pt-5 pr-5 pb-2 no_padding">
      <div class="title text-center pb-5" >Blog</div>
      <div class="">
        <postt v-for="(project, index) in blog" :type="'blog'" :key="index" :name="project.name" :text="project.text" :languages="project.language" :link="project.link"/>
      
      </div>
    </section>
  </div>
</template>
<script>
import postt from "../components/post2.vue"
export default {
  name: "Home",
  components: {
    postt
  },
  data: () => {
    return {
      projects: [
        {
          name: 'Winsusu',
          language: "Javascript, Vue.js, Bootstrap",
          link: 'https://winsusuafrica.com/',
          type: 'project',
          text: `Winsusu is a platform that delivers a human centric and community focused ecosystem, where sustainable impact-driven businesses, solutions and ideas are built.`
        },
        {
          name: 'Sozo hospital application',
          language: "Javascript, Vue.js, Antdv, Firebase",
          link: 'https://sozo-hospital-app.firebaseapp.com/',
          type: 'project',
          text: `Sozo presents a new way of hospital management and automates appointments users have with doctors. `
        },
        {
          name: 'Blue Streak Front end',
          language: "Javascript, Vue.js, Bootstrap",
          link: 'https://github.com/god-of-js/streakfrontend',
          type: 'project',
          text: `Blue streak is an open source platform for streaming movies and many more. `
        },
        {
          name: 'Blue Streak Back end',
          language: "Javascript, node, Express",
          link: 'https://github.com/god-of-js/streak',
          type: 'project',
          text: `Blue streak is an open source platform for streaming movies and many more. `
        },
        {
          name: 'Tech Space',
          language: "Javascript, Vue.js, Bootstrap",
          link: 'https://techspace.africa/',
          type: 'project',
          text: `Techspace is a one-stop technology hub that connects procurement teams with vendors to build and nurture business relationships that add the most value to their success.`
        },
        {
          name: 'Gizmo',
          language: "Typescript, Vue.js, Vue3, Vuetify,  Firebase, Mocha, Chai, CircleCi, Heroku",
          text: `Gizmo is a real estate application where users could purchase land, houses and properties with utmost security due to set protocols.`,
          type: 'project',
          link: 'https://gizmo-front-end.herokuapp.com/'
        },

      ],
      blog: [
        {
          name: 'Building Static Websites with Vuepress',
          language: "Vuepress",
          type: 'blog',
          text: `Vuepress is a minimalistic Vue-powered static site generator by Evan you used for generation of static sites and documentations. A static web page is a web page that is delivered to the user’s web browser exactly as stored, in contrast to dynamic web pages which are generated by a web application( A site meant solely for Visual purposes and passing of information or A site with little to no JavaScript).`,
          link: 'https://medium.com/@Godofjs/building-a-static-website-using-vuepress-b6cc34f70f70?source=friends_link&sk=e59c6851c2c192d06c09d3035120266c'
        },
        {
          name: 'Modularization in Vuejs and Vuex',
          language: "Vuex, Vue, Javascript",
          type: 'blog',
          text: `When writing large front end applications, state management can be quite a difficult and tiring task. \nFor vue.js, a plugin named vuex was created for the purpose of state management. By default it comes with a default folder structure
whose structure could be used in small applications but if used in large applications the codebase would most likely look unreadable, dirty, and over time become difficult to handle.`,
          link:'https://medium.com/swlh/building-large-scale-applications-with-vuex-6d7e8ce0dfef?source=friends_link&sk=cd343c3d40274e766c872839a7854050'
        },
        {
          name: 'Introduction to vuex',
          language: "Vuex, Vue, Javascript",
          type: 'blog',
          text: `Vuex is the official state management library of vuex, It is used for state management as the description implies. It serves as a centralized store for the components in an application, with rules ensuring that the state can only be mutated predictably.
Starting up as a vuejs developer, vuex gave me a tough time, was confusing, and took sometime before I could master it.
In the course of this tutorial, We would be building a book library using vue and firebase. So brace yourself`,
          link:'https://medium.com/swlh/introduction-to-vuex-part-one-f0b6153a90d9?source=friends_link&sk=902a8074ed36d35223a049e645da89a6'
        }
      ]
    }
  }
};
</script>
